### ISSUE TITLE
compile error:Type parameters are invariant

### ISSUE THREAD

**Issue by darcyg** [SimonRichardson/funk#40]
hi stickupkid,
I use haxe 3 RC2 compiler. With the latest version of git.

Under the code in haxe2 OK.

Suggest the following error.

Regard!

D:\HaxeWorks\testDemoNet>nme test windows
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/reactives/Process.hx:143: characte
rs 16-26 : Bool should be cpp.vm.Thread
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:509: characte
rs 24-45 : list : funk.ds.immutable.List<funk.types.Tuple2Type<zip.T1, zip.T2>>
-> item : funk.types.Tuple2Type<zip.T1, zip.T2> -> funk.ds.immutable.List<funk.t
ypes.Tuple2Type<zip.T1, zip.T2>> should be funk.ds.immutable.ListType<funk.types
.Tuple2<zip.T1, zip.T2>> -> funk.types.Tuple2<zip.T1, zip.T2> -> funk.ds.immutab
le.List<funk.types.Tuple2<zip.T1, zip.T2>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:509: characte
rs 24-45 : funk.ds.immutable.List<funk.types.Tuple2Type<zip.T1, zip.T2>> should
be funk.ds.immutable.List<funk.types.Tuple2<zip.T1, zip.T2>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:509: characte
rs 24-45 : Type parameters are invariant
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:509: characte
rs 24-45 : funk.types.Tuple2Type<zip.T1, zip.T2> should be funk.types.Tuple2<zip
.T1, zip.T2>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:666: characte
rs 20-41 : list : funk.ds.immutable.List<funk.types.Tuple2Type<zipWithIndex.T, I
nt>> -> item : funk.types.Tuple2Type<zipWithIndex.T, Int> -> funk.ds.immutable.L
ist<funk.types.Tuple2Type<zipWithIndex.T, Int>> should be funk.ds.immutable.List
Type<funk.types.Tuple2<zipWithIndex.T, Int>> -> funk.types.Tuple2<zipWithIndex.T
, Int> -> funk.ds.immutable.List<funk.types.Tuple2<zipWithIndex.T, Int>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:666: characte
rs 20-41 : funk.ds.immutable.List<funk.types.Tuple2Type<zipWithIndex.T, Int>> sh
ould be funk.ds.immutable.List<funk.types.Tuple2<zipWithIndex.T, Int>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:666: characte
rs 20-41 : Type parameters are invariant
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/List.hx:666: characte
rs 20-41 : funk.types.Tuple2Type<zipWithIndex.T, Int> should be funk.types.Tuple
2<zipWithIndex.T, Int>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/reactives/Behaviour.hx:68: charact
ers 15-75 : funk.reactives.Behaviour<funk.types.Tuple2Type<zip.T1, zip.T2>> shou
ld be funk.reactives.Behaviour<funk.types.Tuple2<zip.T1, zip.T2>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/reactives/Behaviour.hx:68: charact
ers 15-75 : Type parameters are invariant
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/reactives/Behaviour.hx:68: charact
ers 15-75 : funk.types.Tuple2Type<zip.T1, zip.T2> should be funk.types.Tuple2<zi
p.T1, zip.T2>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:245: character
s 54-74 : list : funk.ds.immutable.List<funk.types.Tuple2Type<funk.ds.immutable.
_Map.MapInstanceImpl.K, funk.ds.immutable._Map.MapInstanceImpl.V>> -> item : fun
k.types.Tuple2Type<funk.ds.immutable._Map.MapInstanceImpl.K, funk.ds.immutable._
Map.MapInstanceImpl.V> -> funk.ds.immutable.List<funk.types.Tuple2Type<funk.ds.i
mmutable._Map.MapInstanceImpl.K, funk.ds.immutable._Map.MapInstanceImpl.V>> shou
ld be funk.ds.immutable.List<funk.types.Tuple2<funk.ds.immutable._Map.MapInstanc
eImpl.K, funk.ds.immutable._Map.MapInstanceImpl.V>> -> funk.types.Tuple2<funk.ds
.immutable._Map.MapInstanceImpl.K, funk.ds.immutable._Map.MapInstanceImpl.V> ->
funk.ds.immutable.List<funk.types.Tuple2<funk.ds.immutable._Map.MapInstanceImpl.
K, funk.ds.immutable._Map.MapInstanceImpl.V>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:245: character
s 54-74 : funk.ds.immutable.List<funk.types.Tuple2Type<funk.ds.immutable._Map.Ma
pInstanceImpl.K, funk.ds.immutable._Map.MapInstanceImpl.V>> should be funk.ds.im
mutable.List<funk.types.Tuple2<funk.ds.immutable._Map.MapInstanceImpl.K, funk.ds
.immutable._Map.MapInstanceImpl.V>>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:245: character
s 54-74 : Type parameters are invariant
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:245: character
s 54-74 : funk.types.Tuple2Type<funk.ds.immutable._Map.MapInstanceImpl.K, funk.d
s.immutable._Map.MapInstanceImpl.V> should be funk.types.Tuple2<funk.ds.immutabl
e._Map.MapInstanceImpl.K, funk.ds.immutable._Map.MapInstanceImpl.V>
D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:149: character
s 55-76 : list : funk.ds.immutable.List<funk.types.Tuple2Type<list.K, list.V>> -

> item : funk.types.Tuple2Type<list.K, list.V> -> funk.ds.immutable.List<funk.ty
> pes.Tuple2Type<list.K, list.V>> should be funk.ds.immutable.ListType<funk.types.
> Tuple2<list.K, list.V>> -> funk.types.Tuple2<list.K, list.V> -> funk.ds.immutabl
> e.List<funk.types.Tuple2<list.K, list.V>>
> D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:149: character
> s 55-76 : funk.ds.immutable.List<funk.types.Tuple2Type<list.K, list.V>> should b
> e funk.ds.immutable.List<funk.types.Tuple2<list.K, list.V>>
> D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:149: character
> s 55-76 : Type parameters are invariant
> D:\Motion-Twin\haxe3\haxe\lib\funk/1,6,1/funk/ds/immutable/Map.hx:149: character
> s 55-76 : funk.types.Tuple2Type<list.K, list.V> should be funk.types.Tuple2<list
> .K, list.V>

**Comment by SimonRichardson** [comment]
Yeap this is a know issue in the [haxe compiler](https://code.google.com/p/haxe/issues/detail?id=1726). I've yet to test on the lastest version of haxe (svn source) to see if it's actually been resolved. I did test with the following [patch](https://code.google.com/p/haxe/issues/attachmentText?id=1726&aid=17260015000&name=abstract_type_parameter_variance.patch&token=XbKjCjhg11FDSF3jHU36tkQ-1tE%3A1369303099305), which is different from the actual final fix to the bug, which did resolve the issue. I've been trying to get this resolved for version 3.0, but I'm unsure if it's going to make it. 

If I get time by the end of the day I'll try and build haxe with the lastest code to see if this fixes it.

I'll let you know how it goes...

**Comment by SimonRichardson** [comment]
Didn't meant to close that...

**Comment by darcyg** [comment]
Thank you, I should be compiled with which versions of the SVN (not haxe2.10)?

**Comment by SimonRichardson** [comment]
http://haxe.org/manual/haxe3#build-from-sources

**Comment by SimonRichardson** [comment]
I've just built from haxe3 sources and it does indeed compile correctly, I've also fixed the [signal 1 issue](https://github.com/SimonRichardson/funk/issues/39), so you can use the latest git repo. As soon as haxe 3 is released I'll start making the repo a lot more stable.
